export const SET_REQUESTED_PRODUCT = 'SET_REQUESTED_PRODUCT'

export const SET_REQUESTED_PRODUCT_ID = 'SET_REQUESTED_PRODUCT_ID'




export const TOGGLE_SHOW_FULL_NAVBAR = 'TOGGLE_SHOW_FULL_NAVBAR';
export const TOGGLE_EDITING_MODE = 'TOGGLE_EDITING_MODE'

export const SET_PRODUCTS = 'SET_PRODUCTS'




export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_LOGIN_STATE_TO_TRUE = 'SET_LOGIN_STATE_TO_TRUE';
export const SET_LOGIN_STATE_TO_FALSE = 'SET_LOGIN_STATE_TO_FALSE';


export const INIT_NOTIFICATIONS = 'INIT_NOTIFICATIONS';
export const ADD_A_NOTIFICATION = 'ADD_A_NOTIFICATION';
export const SUBSTRACT_A_NOTIFICATION = 'SUBSTRACT_A_NOTIFICATION';



export const SET_SUPPLIERS = 'SET_SUPPLIERS';
export const SET_BRANDS_AND_MODELS = 'SET_BRANDS_AND_MODELS';


export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PRODUCTS = 'SET_TOTAL_PRODUCTS';
export const SET_INVENTORY_QUERIES = 'SET_INVENTORY_QUERIES';


export const ADD_TOTAL_PRODUCTS = 'ADD_TOTAL_PRODUCTS';


export const SET_PRODUCTS_QUERIES = 'SET_PRODUCTS_QUERIES';
export const SET_SAVED_PRODUCTS_QUERIES_TO_TRUE = 'SET_SAVED_PRODUCTS_QUERIES_TO_TRUE';

export const SET_ERROR = 'SET_ERROR'
